// Category icon names a pack can use, mapped to Material Icons ligatures.
// Must match app/lib/pack/category_icons.dart (a test checks this).
export const CATEGORY_ICONS: Record<string, string> = {
  circle: 'circle',
  star: 'star',
  heart: 'favorite',
  chest: 'inventory_2',
  key: 'vpn_key',
  gem: 'diamond',
  coin: 'paid',
  shield: 'shield',
  book: 'auto_stories',
  scroll: 'description',
  flag: 'flag',
  door: 'door_front',
  bench: 'chair',
  bell: 'notifications',
  boss: 'local_fire_department',
  enemy: 'pest_control',
  npc: 'person',
  shop: 'storefront',
  quest: 'priority_high',
  secret: 'visibility_off',
  puzzle: 'extension',
  travel: 'alt_route',
  save: 'bookmark',
  tool: 'build',
  skill: 'bolt',
  upgrade: 'arrow_circle_up',
  map: 'map',
  music: 'music_note',
  flower: 'local_florist',
  fish: 'set_meal',
  bug: 'bug_report',
  water: 'water_drop',
  note: 'sticky_note_2',
};

export const materialIcon = (name?: string) => CATEGORY_ICONS[name ?? ''] ?? 'circle';
